# Generated by Django 5.1.3 on 2025-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_employee_date_joined_employee_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.AddField(
            model_name='company',
            name='district',
            field=models.CharField(default='Buvayda', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(default="Farg'ona", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='district',
            field=models.CharField(default="Farg'ona", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='region',
            field=models.CharField(default="Farg'ona", max_length=128),
            preserve_default=False,
        ),
    ]
