# Generated by Django 5.1.3 on 2025-01-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_employee_address_company_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('director', 'DIRECTOR'), ('manager', 'MANAGER'), ('employee', 'EMPLOYEE')], max_length=128, null=True),
        ),
    ]
