# Generated by Django 5.1.3 on 2025-01-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_employee_position_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='passport',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
