# Generated by Django 5.1.3 on 2025-01-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_request_employee_request_performer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
