# Generated by Django 5.1.3 on 2025-01-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_companytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project.companytype'),
            preserve_default=False,
        ),
    ]
